### ISSUE TITLE
Save Guild ID on sighting

### ISSUE THREAD

**Issue by Kefkef123** [KentekenBot/KentekenBot#14]
This allows the bot to work in more than one guild, without leaking info from one guild to another.

- [ ] add guildId column to sightings table
- [ ] modify Sightings.insert() to take guild ID
- [ ] modify Sightings.list() to filter guild ID
- [ ] migrate rows with null value to our guild ID

**Comment by peters97** [comment]
Users can be part of multiple guilds, should this be in a separate table?
